export const T = {
  NEXT_STEP: 'NEXT_STEP',
  AUTH: 'AUTH',
  PREVIOUS_STEP: 'PREVIOUS_STEP',
  SAVE_REPORT_DATA: 'SAVE_REPORT_DATA',
  UPDATE_STEP: 'UPDATE_STEP',
  RESET_STEP: 'RESET_STEP',
  GET_ALL_REPORTS_PAGINATION_SUCCESS: 'GET_ALL_REPORTS_PAGINATION_SUCCESS',
  GET_USERS: 'GET_USERS',
  GET_USERS_EXCLUSIVE: 'GET_USERS_EXCLUSIVE',
  GET_ALL_REPORTS: 'GET_ALL_REPORTS',
};
